languageCode: "en-us"
baseUrl: "https://oddish1.xyz"
title: "Oddish1"
theme: "anubis"
paginate: 10
enableRobotsTXT: true

menu:
  main:
  - identifier: archive
    name: Archive
    title: Archive
    url: /posts/
    weight: 0
  - identifier: about
    name: About
    title: About
    url: /about/index.html
    weight: 1
  - identifier: contact
    name: Contact
    title: Contact
    url: /contact/index.html
    weight: 2

params:
  author: "Austin Winslow"
  email: austin@austinwinslow.com # used for microformats
  avatar: "/images/frog.png" # used for microformats
  description: "A personal blog that discusses tutorials, personal stories and insights, and talks about a lot of nerdy things. Topics range from technology, programming, movies, music, and whatever I am inspired to share."
  dateFormat: "2006-01-02"
  paginationSinglePost: true
  style: auto
  mainSections: [ "posts" ] # which sections should be on index/main page
  sectionsWithFullContentOnListPage: [ "notes" ] # for which sections content should be displayed on list pages
  readMore: true # show read more button
  readNextPosts: 5  # show 5 related posts, 0 by default
  disableSummary: false
  toc: true # display Table of Contents
  tocWordCount: 300 # ...when a post is longer than 300 words
  copyCodeButton: true # true by default
  rssAsSocialIcon: true
  mathjax: false # https://www.mathjax.org/
  social:
  - id: github
    name: Oddish1
  - id: mastodon
    url: "https://easymode.im/@Oddish1"

markup:
  goldmark:
    renderer:
      unsafe: true # enable raw HTML in Markdown
